### ISSUE TITLE
Invalid chromosomes

### ISSUE THREAD

**Issue by mmerkin** [currocam/hapne-snakemake#1]
In species with more than 22 autosomes, there is an error:

`Error: Invalid chromosome code '58' on line 103 of .vcf file.
(This is disallowed for humans.  Check if the problem is with your data, or if
you forgot to define a different chromosome set with e.g. --chr-set.)
RuleException:`

I was able to make it work by editing the Snakefile to add --chr-set NUM_AUTOSOMES in rule convert_plink for the LD pipeline.

However, I would prefer not to edit the Snakefile every time I want to look at a different species. Could you make it so that you can specify the number of chromosomes elsewhere e.g. in the config file?

Thanks for working on this tool- it is otherwise very useful.

**Comment by currocam** [comment]
Hi,  
Thanks for reporting. Plink has many flags. I think it's best to allow users to simply pass their own extra flags to plink when needed. For example, I think in your case, your config file could now look like this:

```yaml
data_dir: "example/"
out_dir: "results/"
map_file_suffix: ".shapeit.map"
method: "ld"
maf_threshold: 0.25
nb_points: 1e6
apply_filter: false
plink_extra_flags: "-chr-set 58 no-xy no-mt"
```
Can you confirm this works as intended? If you can think of a better approach, please make a PR.  
Best,  
Curro
